# Generated by Django 5.0.6 on 2024-05-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('isAdmin', models.BooleanField(default=False)),
                ('userImage', models.ImageField(upload_to='', verbose_name='userphotos/%y%m%d')),
                ('address', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=11)),
            ],
        ),
    ]
