# Generated by Django 5.0.6 on 2024-05-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_options'),
        ('userData', '0002_alter_user_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='books',
            field=models.ManyToManyField(null=True, to='book.book'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userImage',
            field=models.ImageField(default='userphotos/240515/profile1.jpg', upload_to='userphotos/%y%m%d'),
        ),
    ]
