# Generated by Django 5.0.6 on 2024-05-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_options'),
        ('userData', '0003_user_books_alter_user_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='books',
            field=models.ManyToManyField(to='book.book'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
