# Generated by Django 5.0.6 on 2024-05-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_book_options'),
        ('userData', '0004_alter_user_address_alter_user_books_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, to='book.book'),
        ),
    ]
