# Generated by Django 5.0.6 on 2024-05-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0005_alter_user_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userImage',
            field=models.ImageField(default='userphotos/240515/profile1.jpg', upload_to='userphotos/%y/%m/%d'),
        ),
    ]
