# Generated by Django 5.0.6 on 2024-05-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0006_alter_user_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userImage',
            field=models.ImageField(default='userphotos/24/05/17/profile1.jpg', upload_to='userphotos/%y/%m/%d'),
        ),
    ]
